config/routes.rb
FunWithTimeZones::Application.routes.draw do
  resources :funs

  root :to => 'funs#index'

end

app/models/fun.rb
class Fun < ActiveRecord::Base
  attr_accessible :crazy_time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/funs_controller.rb
class FunsController < ApplicationController
  # GET /funs
  # GET /funs.json
  def index
    @funs = Fun.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @funs }
    end
  end

  # GET /funs/1
  # GET /funs/1.json
  def show
    @fun = Fun.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fun }
    end
  end

  # GET /funs/new
  # GET /funs/new.json
  def new
    @fun = Fun.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fun }
    end
  end

  # GET /funs/1/edit
  def edit
    @fun = Fun.find(params[:id])
  end

  # POST /funs
  # POST /funs.json
  def create
    @fun = Fun.new(params[:fun])

    respond_to do |format|
      if @fun.save
        format.html { redirect_to @fun, notice: 'Fun was successfully created.' }
        format.json { render json: @fun, status: :created, location: @fun }
      else
        format.html { render action: "new" }
        format.json { render json: @fun.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /funs/1
  # PUT /funs/1.json
  def update
    @fun = Fun.find(params[:id])

    respond_to do |format|
      if @fun.update_attributes(params[:fun])
        format.html { redirect_to @fun, notice: 'Fun was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fun.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funs/1
  # DELETE /funs/1.json
  def destroy
    @fun = Fun.find(params[:id])
    @fun.destroy

    respond_to do |format|
      format.html { redirect_to funs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_date_for_text_field(the_date)
     return the_date.strftime('%d-%m-%Y')
  end
end

app/helpers/funs_helper.rb
module FunsHelper
end

app/views/funs/_form.html.erb
<%= form_for(@fun) do |f| %>
  <% if @fun.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fun.errors.count, "error") %> prohibited this fun from being saved:</h2>

      <ul>
      <% @fun.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :crazy_time %><br />
    <% if @fun.crazy_time and not @fun.crazy_time.blank? %>
        <%= f.text_field :crazy_time, :value => format_date_for_text_field(@fun.crazy_time) %>
    <% else %>
        <%= f.text_field :crazy_time %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/funs/edit.html.erb
<h1>Editing fun</h1>

<%= render 'form' %>

<%= link_to 'Show', @fun %> |
<%= link_to 'Back', funs_path %>

app/views/funs/index.html.erb
<h1>Listing funs</h1>

<table>
  <tr>
    <th>Crazy time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @funs.each do |fun| %>
  <tr>
    <td><%= fun.crazy_time %></td>
    <td><%= link_to 'Show', fun %></td>
    <td><%= link_to 'Edit', edit_fun_path(fun) %></td>
    <td><%= link_to 'Destroy', fun, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fun', new_fun_path %>

app/views/funs/new.html.erb
<h1>New fun</h1>

<%= render 'form' %>

<%= link_to 'Back', funs_path %>

app/views/funs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Crazy time:</b>
  <%= @fun.crazy_time %>
</p>


<%= link_to 'Edit', edit_fun_path(@fun) %> |
<%= link_to 'Back', funs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FunWithTimeZones</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>